### ISSUE TITLE
[FSLeyes_integration] Modify the image loading process to make use of the new 2D support

### ISSUE THREAD

**Issue by Stoyan-I-A** [neuropoly/axondeepseg#229]
A new version of FSLeyes has been released. The 2D support has been added. More info : https://users.fmrib.ox.ac.uk/~paulmc/fsleyes/userdoc/latest/changelog.html
TODO:
- Remove the png to NIfTI conversion
- Check if it is possible to obtain the file path of an already loaded 2D overlay

**Comment by mathieuboudreau** [comment]
Done by @Stoyan-I-A in 3d046e7

**Comment by Stoyan-I-A** [comment]
This isn't done yet. The png to NIfTI conversion is still present in the plugin script because the 2D support on the PyPI & conda-forge versions of FSLeyes is still bugged.

**Comment by Stoyan-I-A** [comment]
This issue was fixed in #182
